Repository cfengine/masterfiles, pull requests merged in 2023-06, with the labels that each got.

#2639 ENT-10274: Adjusted dump.sh for multiple runs in between superhub imports
  templates/federated_reporting/dump.sh
Labels: changelog?

#2651 ENT-10345: Aligned masterfiles module build steps with release tarball
  prepare.sh
Labels: cherry-pick?

#2656 Changelog cleanups
  CHANGELOG.md
Labels: cherry-pick?

#2657 Fix indentation in promises.cf.in
  promises.cf.in
Labels: cherry-pick?

#2591 CFE-4146: Avoided deleting python symlink when sys.bindir is not /var/cfengine/bin
  cfe_internal/update/update_policy.cf
Labels: onhold
